services:
  pomodoro-wev-dev:
    image: pomodoro-wev-dev
    container_name: pomodoro-wev-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - node_modules:/app/node_modules
      - .:/app

volumes:
  node_modules:
    name: node_modules
