services:
  pomodoro-wev-dev:
    image: pomodoro-wev-dev
    container_name: pomodoro-wev-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8081:8080'
    volumes:
      - node_moduless:/app/node_modules
      - .:/app

volumes:
  node_moduless:
    name: node_moduless
